spring.application.name=personal
spring.datasource.url=jdbc:postgresql://localhost:5432/replay
spring.datasource.username=replay_user
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.web=DEBUG
server.port=8085
server.address=0.0.0.0
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.storage.root=/Users/smart/work/replay-storage

logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web=DEBUG
firebase.service-account=firebase/replays-firebase-admin.json
jwt.secret=JIdzib8J6kRCAYA8aaZ8guH5dvcDvHFEu87eT76iCAqoGqyLg0YtKXhZoT+mrb3Wf0REVgfe8NqZBXcuuyAoVg==
jwt.expiration=604800000